name: taskmanager
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.18.0
  flutter_riverpod: ^2.5.1
  cloud_firestore: ^4.15.9
  uuid: ^4.2.2
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  go_router: ^13.0.0
  table_calendar: ^3.0.9
  intl: ^0.19.0

  tuple: ^2.0.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
