// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMFpbWs3Esatj50yv1het8Fh6FuSg3Zuk',
    appId: '1:614395138824:web:87f9ca6ca60ef69562d2bd',
    messagingSenderId: '614395138824',
    projectId: 'task-management-app-73db0',
    authDomain: 'task-management-app-73db0.firebaseapp.com',
    storageBucket: 'task-management-app-73db0.firebasestorage.app',
    measurementId: 'G-T7W9T9T3N3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1RhckwNKGnTmlMaiuterBB8pbeiNfSYY',
    appId: '1:614395138824:android:6146b274c44f143062d2bd',
    messagingSenderId: '614395138824',
    projectId: 'task-management-app-73db0',
    storageBucket: 'task-management-app-73db0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWKn2qiUfPrcioHZ411vIwW1y1jgsifmM',
    appId: '1:614395138824:ios:660bcdfb2369453662d2bd',
    messagingSenderId: '614395138824',
    projectId: 'task-management-app-73db0',
    storageBucket: 'task-management-app-73db0.firebasestorage.app',
    iosBundleId: 'com.example.taskmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWKn2qiUfPrcioHZ411vIwW1y1jgsifmM',
    appId: '1:614395138824:ios:660bcdfb2369453662d2bd',
    messagingSenderId: '614395138824',
    projectId: 'task-management-app-73db0',
    storageBucket: 'task-management-app-73db0.firebasestorage.app',
    iosBundleId: 'com.example.taskmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMFpbWs3Esatj50yv1het8Fh6FuSg3Zuk',
    appId: '1:614395138824:web:8f1c3216ca0f38dd62d2bd',
    messagingSenderId: '614395138824',
    projectId: 'task-management-app-73db0',
    authDomain: 'task-management-app-73db0.firebaseapp.com',
    storageBucket: 'task-management-app-73db0.firebasestorage.app',
    measurementId: 'G-J3PX0D0LSE',
  );

}